spring.application.name=main
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5070/merradb
spring.datasource.username=merra-user
spring.datasource.password=password
spring.liquibase.change-log=db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=merra_schema
spring.liquibase.liquibase-schema=merra_schema
spring.liquibase.url=jdbc:postgresql://localhost:5070/merradb
spring.liquibase.user=merra-user
spring.liquibase.password=password
spring.app.jwt.secret=5da7abccd68264a5dadf70e16ccd2a48e5174651a08af2a366f8a28e39c88c0c
spring.app.jwt.access-token=480000
spring.app.details.api.website=https://restcountries.com/v3.1
